final List<String> phrasesJp = [
  // 🗣 2割：日本語
  "おはよう！",
  "今日も元気？",
  "調子はどう？",
  "いい朝だね！",
  "まだ眠い？",
  "朝ごはん食べた？",
  "今日もがんばろ！",
  "無理しすぎてない？",
  "天気いいね！",
  "最近どう？",
  "ちょっと休憩しよっか？",
  "水飲んだ？",
  "外出た？",
  "笑顔が一番だね！",
  "深呼吸しよ！",
  "いい感じだね！",
  "昨日はよく寝れた？",
  "ちょっと話そ！",
  "今どんな気分？",
  "おつかれさま！",
  "リラックスしてね！",
  "一歩ずつでOK！",
  "今日はどんな予定？",
  "コーヒー飲んだ？",
  "疲れてない？",
  "たまには休もうね！",
  "夢に近づいてるね！",
  "よくやってるよ！",
  "今日はゆっくり行こ！",
  "焦らずいこう！",
  "そのままで大丈夫！",
  "やる気あるね！",
  "最近ハマってることある？",
  "いい波きてるね！",
  "今日は何話す？",
  "昨日なにしてた？",
  "元気出してこ！",
  "気分転換しよ！",
  "英語の練習しよ！",
  "一緒に話そ！",

  // 🌍 8割：カタコト英語 or Easy English
  "Hey! How’s it going?",
  "Good morning sunshine!",
  "Yo! What’s up today?",
  "Feeling good?",
  "Let’s crush the day!",
  "You look ready to roll!",
  "Rise and shine!",
  "Time to wake that brain up!",
  "Ready to talk?",
  "What’s poppin’?",
  "Let’s make today awesome!",
  "Smile! You look better that way 😄",
  "Let’s vibe together!",
  "You got that energy today!",
  "Wanna chat for a bit?",
  "I’m feeling talkative today!",
  "Let’s talk about something fun!",
  "You seem full of ideas!",
  "Coffee time?",
  "Good mood only, okay?",
  "Let’s start strong!",
  "Today’s gonna be amazing!",
  "What’s the plan, my friend?",
  "Feeling inspired?",
  "You bring good vibes!",
  "Let’s make some noise!",
  "Tell me something cool!",
  "It’s your time to shine!",
  "What made you smile today?",
  "You ready to roll?",
  "Hey hey! I missed you!",
  "Let’s warm up with a chat!",
  "Your energy’s contagious!",
  "You sound happy today!",
  "That smile suits you!",
  "Let’s get things started!",
  "You and me — good combo!",
  "Let’s make some magic happen!",
  "High five! ✋",
  "You look fired up today!",
  "You ready for another great day?",
  "Let’s make today count!",
  "Yo! You in a good mood?",
  "I like your vibe already!",
  "You always bring good energy!",
  "Let’s talk about something random!",
  "Feeling fresh today?",
  "New day, new fun!",
  "How’s your coffee?",
  "You sound more confident lately!",
  "That’s the spirit!",
  "Wanna tell me a secret?",
  "You’re glowing today!",
  "I’ve got a good feeling about today!",
  "Let’s make this moment cool!",
  "What made you laugh today?",
  "I like your style!",
  "You always make things fun!",
  "Let’s chill and talk.",
  "You’re my favorite person today!",
  "Your smile could light up a room!",
  "Let’s keep this energy going!",
  "You look unstoppable!",
  "That’s the vibe I like!",
  "You’re shining today!",
  "Wanna do something exciting?",
  "You got that spark!",
  "Hey superstar, what’s new?",
  "It’s a perfect day for good talks!",
  "You’re full of good energy today!",
  "Let’s make it a good one!",
  "Feeling extra today?",
  "You always make me laugh!",
  "Let’s do something spontaneous!",
  "You’re totally in the zone!",
  "You’re glowing with confidence!",
  "Hey, I like that energy!",
  "Let’s chat before the day flies by!",
  "You’re unstoppable today!",
  "Let’s gooo!",
  "You ready to have some fun?",
  "Let’s make this a chill day!",
  "You got that weekend energy!",
  "Feeling lazy or motivated?",
  "Let's talk about random stuff!",
  "Good to see you again!",
  "You look like you’re in a good mood!",
  "Wanna share your thoughts?",
  "Tell me your latest idea!",
  "You seem excited today!",
  "You’ve got that positive aura!",
  "How’s everything going?",
  "Let's make today productive!",
  "Feeling creative today?",
  "You look like a dreamer!",
  "What’s your plan for the day?",
  "Let’s laugh for no reason!",
  "You sound full of energy!",
  "You're such good company!",
  "You ready to crush it today?",
  "Hey champ, what’s next?",
  "Your vibe is unmatched!",
  "You always bring sunshine!",
  "What’s on your playlist today?",
  "You got this, no doubt!",
  "You make it look easy!",
  "Let's talk about your goals!",
  "Feeling lucky today?",
  "You’re glowing like the sun!",
  "Hey legend, how’s life?",
  "You seem extra cool today!",
  "Let's turn this day around!",
  "You’re seriously awesome!",
  "Let’s start with something fun!",
  "You’re killing it lately!",
  "You always know how to smile!",
  "What’s something funny you saw?",
  "You got that happy face again!",
  "I like your confidence!",
  "Let's make this day sparkle!",
  "Yo! You ready to rock today?",
  "Let’s make this day unforgettable!",
  "You’re shining brighter than ever!",
  "Wanna do something crazy fun?",
  "Let's keep the good vibes rolling!",
  "You make everything more fun!",
  "Let’s bring that fire today! 🔥",
  "You got that winner energy!",
  "Hey! Let’s make some noise!",
  "You always surprise me!",
  "Feeling awesome today?",
  "You’re a whole vibe!",
  "Let's go make memories!",
  "That smile just made my day!",
  "You look unstoppable today!",
  "Let's talk about something wild!",
  "You’ve got amazing energy!",
  "I like your spirit!",
  "Let’s do something legendary!",
  "You’re my motivation today!",
  "Let's talk like old friends!",
  "You’re pure sunshine!",
  "Let’s keep that smile going!",
  "You make good days better!",
  "Let's bring out the good energy!",
  "You’re absolutely glowing!",
  "Let’s chase good vibes only!",
  "You’re on fire today!",
  "Hey! I love that smile!",
  "Let's start a good conversation!",
  "You're the reason today feels bright!",
  "Let’s celebrate small wins!",
  "You sound so alive!",
  "Let's turn up the energy!",
  "You're full of life today!",
  "Let's talk and laugh it out!",
  "You make this moment fun!",
  "Let's go for good energy only!",
  "You're one of a kind!",
  "Let's end the day smiling!",
  "See you shining, superstar!",
];
