// 🗣 English Phrases for the speech bubble
// You can freely expand this list up to 200 lines or more.

final List<String> phrasesEn = [
  "Hey, what’s up?",
  "You look motivated today.",
  "Let's practice English together.",
  "What do you want to talk about?",
  "I like your energy today.",
  "Take a deep breath.",
  "Keep going, you're doing great.",
  "What's your dream?",
  "Do you like traveling?",
  "Let's make today productive.",
  "It's a great day to learn something new.",
  "Stay curious — it’s your superpower.",
  "Mistakes mean you're growing.",
  "One step at a time, that’s how progress works.",
  "Speak with confidence, even if you're unsure.",
  "Every word you say makes you better.",
  "English is just a tool — express your mind.",
  "Be proud of every small step.",
  "Let’s have fun learning!",
  "You got this 🔥",
  "What inspires you lately?",
  "Tell me something funny.",
  "If you could travel anywhere, where would you go?",
  "Learning never stops.",
  "Silence can be powerful too.",
  "Smile while you speak 😊",
  "You’re doing better than you think.",
  "Challenge yourself — it’s worth it.",
  "You’re already improving.",
  "Confidence grows with practice.",
  "Let’s keep the vibe positive!",
  "What’s one thing you love about yourself?",
  "English connects the world.",
  "Keep your mind open and light.",
  "Every sentence is a new step forward.",
  "Let’s make it fun, not perfect.",
  "You can express anything — just try.",
  "Feel free to be yourself.",
  "Don’t rush, enjoy the process.",
  "Say it like you mean it.",
  "Let’s make your words shine today.",
  "Don’t compare, just continue.",
  "You’re unique — that’s your strength.",
  "Think less, talk more.",
  "It’s okay to pause and think.",
  "Your voice matters.",
  "Let’s make mistakes proudly!",
  "Talk like nobody’s judging.",
  "Small talks build big confidence.",
  "Imagine you’re talking to a friend.",
  "Make your English sound alive.",
];
